version: '3.8'

services:
  stock-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-test_key}
      - NEWS_API_KEY=${NEWS_API_KEY:-test_key}
    env_file:
      - .env
    volumes:
      # Mount source code for live reloading
      - .:/app
      # Exclude virtual environment and cache
      - /app/venv
      - /app/__pycache__
    restart: unless-stopped
    stdin_open: true
    tty: true 